### PR TITLE
rename log -> tail

### PR DESCRIPTION
**Pull request by Wing924**
rename log -> tail (fix: #7 )
add makefile
delete unused vendor (by `dep ensure`)

### CODE REVIEW

**Comment by l2isbad** [comment]
Are you sure about all those deletions?

**Comment by Wing924** [comment]
Yes, they're test, readme, etc.

**Comment by l2isbad** [comment]
Ok, then tell me when you are ready

**Comment by Wing924** [comment]
it's ready for this PR :)

**Pull request merged**
