### PR TITLE
[Super WIP] Refactor job

### LINKED ISSUE #19: Refactor Plugin/Job
Currently, GoDPlugin and job part are very complex and hard to read.
I'm doing something refactor now.

My goal:

- [ ]  The main should be responsible for args and ENV.
- [ ]  The GoDPlugin should be responsible for controlling jobs and global time tick.
- [ ] The jobs should be responsible for doing real tasks.

### PR DESCRIPTION
**Pull request by Wing924**
super WIP, don't merge it.
Fix #19 

- [x] handle signal
- [ ] unit test
- [ ] etc.

### CODE REVIEW

**Comment by l2isbad** [comment]
So you want to rewrite the whole thing? Hm,

**Comment by Wing924** [comment]
I won't touch the module part, just plugin part and don't change the interface.

**Comment by l2isbad** [comment]
Ok, let's see

**Comment by Wing924** [comment]
I’m on vacation till 16 Aug. I’ll work for it after that. Have a nice vacation.

**Comment by l2isbad** [comment]
@Wing924 any news?

**Comment by Wing924** [comment]
I was busy for last month, but I think I can finish it in less than 2 weeks.

**Comment by l2isbad** [comment]
Nice. @Wing924 can i have a chat with you? For a faster communication. Do you use telegram? If not what messenger do you prefer?

**Comment by Wing924** [comment]
@l2isbad 
I don't have that. I'll create a new account.

**Comment by l2isbad** [comment]
send me your phone number (i need it to add your contact) to ilyamaschenko@gmail.com

**Pull request closed without merging**
