### PR TITLE
helpers.tail optimizations

### PR DESCRIPTION
**Pull request by l2isbad**
todo:
- [x] humanize `helpers.tail`

### CODE REVIEW

**Comment by Wing924** [comment]
weblog format is just space-separated values format. we don’t need regexp to parse.
Go’s regexp is really slow.

**Comment by l2isbad** [comment]
10 goroutines 1mil rows: 1.098035678s vs 1.234807467s (csv wins).

**Comment by Wing924** [comment]
I think I/O can't be parallel and I/O time is much more than parsing time.
Should we really need parallel parsing?
Let's bench it first.

**Comment by l2isbad** [comment]
> Should we really need parallel parsing?

2.5s vs 9s (10 vs 1 goroutines) on my SSD (1771561 lines)

**Comment by Wing924** [comment]
> 2.5s vs 9s (10 vs 1 goroutines) on my SSD (1771561 lines)

Whose access log can be 1.7M lines/s ?
Normal apache application: 500/s, high traffic nginx: 10k/s

**Comment by l2isbad** [comment]
100k rows:

- regexp:
 1 goroutine: 520.747452ms
 10 goroutine: 164.083987ms

- csv:
 1 goroutine: 333.744791ms
 10 goroutine: 153.721464ms

**Comment by l2isbad** [comment]
Still it makes much sense even for 20k/s according my tests. So yes, we need concurent parsing.

**Comment by Wing924** [comment]
> Still it makes much sense even for 20k/s according my tests. So yes, we need concurent parsing.

I agree. Let's make the default count of workers to 1.

**Comment by l2isbad** [comment]
And i see no big dif between `csv` and `regex` parse on 20k/s

- 1 goroutine: 74ms vs 87ms
- 10 goroutine: both 35-40ms

**Comment by Wing924** [comment]
> And i see no big dif between csv and regex parse on 20k/s

could you show me your bench code?

**Comment by l2isbad** [comment]
Regex result depends on regex, ofc

<details><summary>test</summary>
<p>

```go
import (
	"bufio"
	"encoding/csv"
	"fmt"
	"os"
	"regexp"
	"strings"
	"time"
)

var apacheV1 = strings.Join([]string{
	`(?P<address>[\da-f.:]+|localhost) -.*?"`,
	`(?P<request>[^"]*)" `,
	`(?P<code>[1-9]\d{2}) `,
	`(?P<bytes_sent>\d+|-)`,
}, "")

var full = regexp.MustCompile(apacheV1)

func main() {
	c := make(chan string)
	for i := 0; i < 10; i++ {
		go workerRegexp(c)
	}
	f, _ := os.Open("123.txt")

	s := bufio.NewScanner(f)

	t := time.Now()
	for s.Scan() {
		c <- s.Text()
	}
	fmt.Println(time.Since(t))

}

func workerRegexp(doCh chan string) {
	for v := range doCh {
		full.FindStringSubmatch(v)
	}
}

func workerCsv(doCh chan string) {
	for v := range doCh {
		vv := csv.NewReader(strings.NewReader(v))
		vv.Comma = ' '
		_, _ = vv.Read()
	}
}

```

</p>
</details>

**Comment by Wing924** [comment]
As far as I know, apache, squid and nginx's timestamp format are `[07/Dec/2016:11:04:37 +0100]`.
If users have different format, they can use custom format.

**Comment by l2isbad** [comment]
Ok, regex searches is **very** dependent on `regex` itself. If it's `bad`, then the search speed goes down super bad (10/20/30x slower) :smile:

**Comment by Wing924** [comment]
This is my bench result:
```
// just read 10k lines
BenchmarkRead10k-4      	    2000	    548,457 ns/op	 1958313 B/op	       6 allocs/op
// read 100k lines
BenchmarkRead100k-4     	     200	   7,373,279 ns/op	19554729 B/op	       6 allocs/op

// using regex
BenchmarkRegExp10k-4    	      50	  29,057,109 ns/op	 3617627 B/op	   30004 allocs/op
BenchmarkRegExp100k-4   	       5	 331,437,072 ns/op	36137592 B/op	  300004 allocs/op

// using CSV
BenchmarkCSV10k-4       	     200	   5,896,673 ns/op	 1872160 B/op	   10016 allocs/op
BenchmarkCSV100k-4      	     300	   5,352,024 ns/op	 1872161 B/op	   10016 allocs/op
```

**Comment by Wing924** [comment]
This is my bench code:
```go
package plugin

import (
	"bufio"
	"encoding/csv"
	"io"
	"io/ioutil"
	"os"
	"regexp"
	"strings"
	"testing"
)

var log10k = "access.10k.log"
var log100k = "access.100k.log"

var regex = regexp.MustCompile(strings.Join([]string{
	`(?P<address>[\da-f.:]+|localhost) -.*?"`,
	`(?P<request>[^"]*)" `,
	`(?P<code>[1-9]\d{2}) `,
	`(?P<bytes_sent>\d+|-)`,
}, ""))

func BenchmarkRead10k(b *testing.B) {
	for i := 0; i < b.N; i++ {
		ioutil.ReadFile(log10k)
	}
}
func BenchmarkRead100k(b *testing.B) {
	for i := 0; i < b.N; i++ {
		ioutil.ReadFile(log100k)
	}
}

func BenchmarkRegExp10k(b *testing.B) {
	for i := 0; i < b.N; i++ {
		f, _ := os.Open(log10k)
		r := bufio.NewScanner(f)
		for r.Scan() {
			line := r.Text()
			regex.FindStringSubmatch(line)
		}
	}
}
func BenchmarkRegExp100k(b *testing.B) {
	for i := 0; i < b.N; i++ {
		f, _ := os.Open(log100k)
		r := bufio.NewScanner(f)
		for r.Scan() {
			line := r.Text()
			regex.FindStringSubmatch(line)
		}
	}
}

func BenchmarkCSV10k(b *testing.B) {
	for i := 0; i < b.N; i++ {
		f, _ := os.Open(log10k)
		f2 := bufio.NewReader(f)
		r := csv.NewReader(f2)
		r.ReuseRecord = true
		r.Comma = ' '
		for {
			_, err := r.Read()
			if err == io.EOF {
				break
			}
		}
	}
}

func BenchmarkCSV100k(b *testing.B) {
	for i := 0; i < b.N; i++ {
		f, _ := os.Open(log10k)
		f2 := bufio.NewReader(f)
		r := csv.NewReader(f2)
		r.ReuseRecord = true
		r.Comma = ' '
		for {
			_, err := r.Read()
			if err == io.EOF {
				break
			}
		}
	}
}
```

**Comment by Wing924** [comment]
CSV is *much* faster than regex.

**Comment by l2isbad** [comment]
Your CSV tests are wrong,  you have to read 1 line at a time. Tail returns 1 line, not slice of lines.

**Comment by Wing924** [comment]
> Your CSV tests are wrong, you have to read 1 line at a time. Tail returns 1 line, not slice of lines.

I use loop until EOF
```go
for {
			_, err := r.Read()
			if err == io.EOF {
				break
			}
		}
```

**Comment by l2isbad** [comment]
I see, but you pass the whole file to `csv`. This is not how `web_log` works.

**Comment by Wing924** [comment]
> I see, but you pass the whole file to csv. This is not how web_log works.

You can pass a `io.Reader`, right?

**Comment by l2isbad** [comment]
Give me a direction, that's a good practive for me :smile_cat:

**Comment by Wing924** [comment]
> You can, but how it supposed to work? Tail (or some other func) should seek and return a *File ?

You can return `[]byte` or `*os.FIle` with `Seek(...)`

**Comment by l2isbad** [comment]
Nice, i think i got it, will do :+1: i am not even a programmer ilr lol, so i really appreciate your help :smile:

**Comment by l2isbad** [comment]
> *os.FIle with Seek(...)
i think `ReadCloser` is enough, i can get last pos before returning
1. seek to last, save last
2. seek to end, get end
3. seek to last, return `ReadCloser`

**Comment by l2isbad** [comment]
Ok, i am merging it, will do other web_log optiomization in next

**Comment by l2isbad** [comment]
Any comments @Wing924 ?

**Pull request merged**
